name: Devcontainer test 
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test: 
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "Publish Templates"
        uses: devcontainers/action@v1